#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';



use Symfony\Component\Console\Application;
use App\Commands\GlorfCommand;
use App\Commands\FlubCommand;
$application = new Application();
$application->add(new GlorfCommand());
$application->add(new FlubCommand());
$application->run();